<a href="https://www.kaggle.com/code/enockmokua/z-score-for-outlier-detection?scriptVersionId=96583392" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

## Z-Score method.
* The z-score is also reffered to as the **standard score**.
*  It helps us conceptualize how many standard deviations away a data value is from the mean and how bi or small the value is than the mean.
*  Mathematically the z-score is given by the formula **Z = (x - mean)/y**

> Where x = data value and y = standard deviation 

#### Z-Score and outliers.
* During the computation of teh z-score we expect the z-score of the data to fall within the range of **-3 < x > 3** if it falls out of this range this indicates that the data point is quite unique and this value might be an outlier.

### Examples.

Lets generate random data and walk the talk.

In [1]:
#importing libraries for use.
import numpy as np
import random

#generating random data for the students 
data = [random.randint(0, 100) for i in range(10)]
print(data)

[91, 88, 68, 61, 98, 8, 28, 89, 59, 94]

In [2]:
#calculating the mean and standard deviation of the data
dmean  = np.mean(data)
dstd = np.std(data)
print ('Mean of the data is : ' + str(dmean))
print ('Standard deviation of the data is : ' + str(dstd))

Mean of the data is : 68.4
Standard deviation of the data is : 28.76525682138089

In [3]:
#calculating the z zscore with the threshold at 3
threshold = 3
outlier = []
for i in data:
    z = (i - dmean) / dstd
    if z > threshold:
        outlier.append(i)
print ('outlier in the dataset is', outlier)

outlier in the dataset is []

* Another way of calculating the z-score is using the scipy module

In [4]:
#using scipy.stats
from scipy import stats
stats.zscore(data, axis = None)

array([ 0.78567002,  0.68137754, -0.01390566, -0.25725479,  1.02901915,
       -2.09975528, -1.40447208,  0.7161417 , -0.32678311,  0.8899625 ])

In [5]:
# Using a Sample Pandas Dataframe
import pandas as pd

df = pd.DataFrame.from_dict({
    'Name': ['Nik', 'Kate', 'Joe', 'Mitch', 'Alana'],
    'Age': [32, 30, 67, 34, 20],
    'Income': [800000, 9000, 4500, 2300, 12000],
    'Education' : [5, 7, 3, 4, 4]
})
df.head()

    Name  Age  Income  Education
0    Nik   32  800000          5
1   Kate   30    9000          7
2    Joe   67    4500          3
3  Mitch   34    2300          4
4  Alana   20   12000          4

In [6]:
#creating a column with the normalized values from the income column 
df['Income Zscore'] = stats.zscore(df.Income)
df.head()

    Name  Age  Income  Education  Income Zscore
0    Nik   32  800000          5       1.999886
1   Kate   30    9000          7      -0.493509
2    Joe   67    4500          3      -0.507694
3  Mitch   34    2300          4      -0.514629
4  Alana   20   12000          4      -0.484053

In [7]:
#converting our dataframe columns into zscores using pandas.apply() method
df = df.select_dtypes(include = 'number').apply(stats.zscore).drop(columns = ['Income Zscore'])
df.head()

        Age    Income  Education
0 -0.288493  1.999886   0.294884
1 -0.413925 -0.493509   1.769303
2  1.906565 -0.507694  -1.179536
3 -0.163061 -0.514629  -0.442326
4 -1.041085 -0.484053  -0.442326